(function () {
// ==UserScript==
// @name           Google Search Direct
// @namespace      http://blog.thrsh.net
// @author         daYOda (THRSH)
// @description    Eliminate Google redirect search results
// @version        1.1
// @updateURL      https://github.com/cecekpawon/Google-Search-Direct/raw/master/releases/Google-Search-Direct.meta.js
// @downloadURL    https://github.com/cecekpawon/Google-Search-Direct/raw/master/releases/Google-Search-Direct.user.js
// @grant          none
// @match          https://www.google.com/search* 
// @match          https://www.google.com/?*q=* 
// @match          https://www.google.ac/search* 
// @match          https://www.google.ac/?*q=* 
// @match          https://www.google.ad/search* 
// @match          https://www.google.ad/?*q=* 
// @match          https://www.google.ae/search* 
// @match          https://www.google.ae/?*q=* 
// @match          https://www.google.com.af/search* 
// @match          https://www.google.com.af/?*q=* 
// @match          https://www.google.com.ag/search* 
// @match          https://www.google.com.ag/?*q=* 
// @match          https://www.google.com.ai/search* 
// @match          https://www.google.com.ai/?*q=* 
// @match          https://www.google.al/search* 
// @match          https://www.google.al/?*q=* 
// @match          https://www.google.am/search* 
// @match          https://www.google.am/?*q=* 
// @match          https://www.google.co.ao/search* 
// @match          https://www.google.co.ao/?*q=* 
// @match          https://www.google.com.ar/search* 
// @match          https://www.google.com.ar/?*q=* 
// @match          https://www.google.as/search* 
// @match          https://www.google.as/?*q=* 
// @match          https://www.google.at/search* 
// @match          https://www.google.at/?*q=* 
// @match          https://www.google.com.au/search* 
// @match          https://www.google.com.au/?*q=* 
// @match          https://www.google.az/search* 
// @match          https://www.google.az/?*q=* 
// @match          https://www.google.ba/search* 
// @match          https://www.google.ba/?*q=* 
// @match          https://www.google.com.bd/search* 
// @match          https://www.google.com.bd/?*q=* 
// @match          https://www.google.be/search* 
// @match          https://www.google.be/?*q=* 
// @match          https://www.google.bf/search* 
// @match          https://www.google.bf/?*q=* 
// @match          https://www.google.bg/search* 
// @match          https://www.google.bg/?*q=* 
// @match          https://www.google.com.bh/search* 
// @match          https://www.google.com.bh/?*q=* 
// @match          https://www.google.bi/search* 
// @match          https://www.google.bi/?*q=* 
// @match          https://www.google.bj/search* 
// @match          https://www.google.bj/?*q=* 
// @match          https://www.google.com.bn/search* 
// @match          https://www.google.com.bn/?*q=* 
// @match          https://www.google.com.bo/search* 
// @match          https://www.google.com.bo/?*q=* 
// @match          https://www.google.com.br/search* 
// @match          https://www.google.com.br/?*q=* 
// @match          https://www.google.bs/search* 
// @match          https://www.google.bs/?*q=* 
// @match          https://www.google.bt/search* 
// @match          https://www.google.bt/?*q=* 
// @match          https://www.google.co.bw/search* 
// @match          https://www.google.co.bw/?*q=* 
// @match          https://www.google.by/search* 
// @match          https://www.google.by/?*q=* 
// @match          https://www.google.com.bz/search* 
// @match          https://www.google.com.bz/?*q=* 
// @match          https://www.google.co.nz/search* 
// @match          https://www.google.co.nz/?*q=* 
// @match          https://www.google.com.kh/search* 
// @match          https://www.google.com.kh/?*q=* 
// @match          https://www.google.cc/search* 
// @match          https://www.google.cc/?*q=* 
// @match          https://www.google.cd/search* 
// @match          https://www.google.cd/?*q=* 
// @match          https://www.google.cf/search* 
// @match          https://www.google.cf/?*q=* 
// @match          https://www.google.cat/search* 
// @match          https://www.google.cat/?*q=* 
// @match          https://www.google.cg/search* 
// @match          https://www.google.cg/?*q=* 
// @match          https://www.google.ch/search* 
// @match          https://www.google.ch/?*q=* 
// @match          https://www.google.ci/search* 
// @match          https://www.google.ci/?*q=* 
// @match          https://www.google.co.ck/search* 
// @match          https://www.google.co.ck/?*q=* 
// @match          https://www.google.cl/search* 
// @match          https://www.google.cl/?*q=* 
// @match          https://www.google.cm/search* 
// @match          https://www.google.cm/?*q=* 
// @match          https://www.google.cn/search* 
// @match          https://www.google.cn/?*q=* 
// @match          https://www.google.com.co/search* 
// @match          https://www.google.com.co/?*q=* 
// @match          https://www.google.co.cr/search* 
// @match          https://www.google.co.cr/?*q=* 
// @match          https://www.google.com.cu/search* 
// @match          https://www.google.com.cu/?*q=* 
// @match          https://www.google.cv/search* 
// @match          https://www.google.cv/?*q=* 
// @match          https://www.google.com.cy/search* 
// @match          https://www.google.com.cy/?*q=* 
// @match          https://www.google.cz/search* 
// @match          https://www.google.cz/?*q=* 
// @match          https://www.google.de/search* 
// @match          https://www.google.de/?*q=* 
// @match          https://www.google.dj/search* 
// @match          https://www.google.dj/?*q=* 
// @match          https://www.google.dk/search* 
// @match          https://www.google.dk/?*q=* 
// @match          https://www.google.dm/search* 
// @match          https://www.google.dm/?*q=* 
// @match          https://www.google.com.do/search* 
// @match          https://www.google.com.do/?*q=* 
// @match          https://www.google.dz/search* 
// @match          https://www.google.dz/?*q=* 
// @match          https://www.google.com.ec/search* 
// @match          https://www.google.com.ec/?*q=* 
// @match          https://www.google.ee/search* 
// @match          https://www.google.ee/?*q=* 
// @match          https://www.google.com.eg/search* 
// @match          https://www.google.com.eg/?*q=* 
// @match          https://www.google.es/search* 
// @match          https://www.google.es/?*q=* 
// @match          https://www.google.com.et/search* 
// @match          https://www.google.com.et/?*q=* 
// @match          https://www.google.fi/search* 
// @match          https://www.google.fi/?*q=* 
// @match          https://www.google.com.fj/search* 
// @match          https://www.google.com.fj/?*q=* 
// @match          https://www.google.fm/search* 
// @match          https://www.google.fm/?*q=* 
// @match          https://www.google.fr/search* 
// @match          https://www.google.fr/?*q=* 
// @match          https://www.google.ga/search* 
// @match          https://www.google.ga/?*q=* 
// @match          https://www.google.ge/search* 
// @match          https://www.google.ge/?*q=* 
// @match          https://www.google.gf/search* 
// @match          https://www.google.gf/?*q=* 
// @match          https://www.google.gg/search* 
// @match          https://www.google.gg/?*q=* 
// @match          https://www.google.com.gh/search* 
// @match          https://www.google.com.gh/?*q=* 
// @match          https://www.google.com.gi/search* 
// @match          https://www.google.com.gi/?*q=* 
// @match          https://www.google.gl/search* 
// @match          https://www.google.gl/?*q=* 
// @match          https://www.google.gm/search* 
// @match          https://www.google.gm/?*q=* 
// @match          https://www.google.gp/search* 
// @match          https://www.google.gp/?*q=* 
// @match          https://www.google.gr/search* 
// @match          https://www.google.gr/?*q=* 
// @match          https://www.google.com.gt/search* 
// @match          https://www.google.com.gt/?*q=* 
// @match          https://www.google.gy/search* 
// @match          https://www.google.gy/?*q=* 
// @match          https://www.google.com.hk/search* 
// @match          https://www.google.com.hk/?*q=* 
// @match          https://www.google.hn/search* 
// @match          https://www.google.hn/?*q=* 
// @match          https://www.google.hr/search* 
// @match          https://www.google.hr/?*q=* 
// @match          https://www.google.ht/search* 
// @match          https://www.google.ht/?*q=* 
// @match          https://www.google.hu/search* 
// @match          https://www.google.hu/?*q=* 
// @match          https://www.google.co.id/search* 
// @match          https://www.google.co.id/?*q=* 
// @match          https://www.google.iq/search* 
// @match          https://www.google.iq/?*q=* 
// @match          https://www.google.ie/search* 
// @match          https://www.google.ie/?*q=* 
// @match          https://www.google.co.il/search* 
// @match          https://www.google.co.il/?*q=* 
// @match          https://www.google.im/search* 
// @match          https://www.google.im/?*q=* 
// @match          https://www.google.co.in/search* 
// @match          https://www.google.co.in/?*q=* 
// @match          https://www.google.io/search* 
// @match          https://www.google.io/?*q=* 
// @match          https://www.google.is/search* 
// @match          https://www.google.is/?*q=* 
// @match          https://www.google.it/search* 
// @match          https://www.google.it/?*q=* 
// @match          https://www.google.je/search* 
// @match          https://www.google.je/?*q=* 
// @match          https://www.google.com.jm/search* 
// @match          https://www.google.com.jm/?*q=* 
// @match          https://www.google.jo/search* 
// @match          https://www.google.jo/?*q=* 
// @match          https://www.google.co.jp/search* 
// @match          https://www.google.co.jp/?*q=* 
// @match          https://www.google.co.ke/search* 
// @match          https://www.google.co.ke/?*q=* 
// @match          https://www.google.ki/search* 
// @match          https://www.google.ki/?*q=* 
// @match          https://www.google.kg/search* 
// @match          https://www.google.kg/?*q=* 
// @match          https://www.google.co.kr/search* 
// @match          https://www.google.co.kr/?*q=* 
// @match          https://www.google.com.kw/search* 
// @match          https://www.google.com.kw/?*q=* 
// @match          https://www.google.kz/search* 
// @match          https://www.google.kz/?*q=* 
// @match          https://www.google.la/search* 
// @match          https://www.google.la/?*q=* 
// @match          https://www.google.com.lb/search* 
// @match          https://www.google.com.lb/?*q=* 
// @match          https://www.google.com.lc/search* 
// @match          https://www.google.com.lc/?*q=* 
// @match          https://www.google.li/search* 
// @match          https://www.google.li/?*q=* 
// @match          https://www.google.lk/search* 
// @match          https://www.google.lk/?*q=* 
// @match          https://www.google.co.ls/search* 
// @match          https://www.google.co.ls/?*q=* 
// @match          https://www.google.lt/search* 
// @match          https://www.google.lt/?*q=* 
// @match          https://www.google.lu/search* 
// @match          https://www.google.lu/?*q=* 
// @match          https://www.google.lv/search* 
// @match          https://www.google.lv/?*q=* 
// @match          https://www.google.com.ly/search* 
// @match          https://www.google.com.ly/?*q=* 
// @match          https://www.google.co.ma/search* 
// @match          https://www.google.co.ma/?*q=* 
// @match          https://www.google.md/search* 
// @match          https://www.google.md/?*q=* 
// @match          https://www.google.me/search* 
// @match          https://www.google.me/?*q=* 
// @match          https://www.google.mg/search* 
// @match          https://www.google.mg/?*q=* 
// @match          https://www.google.mk/search* 
// @match          https://www.google.mk/?*q=* 
// @match          https://www.google.ml/search* 
// @match          https://www.google.ml/?*q=* 
// @match          https://www.google.com.mm/search* 
// @match          https://www.google.com.mm/?*q=* 
// @match          https://www.google.mn/search* 
// @match          https://www.google.mn/?*q=* 
// @match          https://www.google.ms/search* 
// @match          https://www.google.ms/?*q=* 
// @match          https://www.google.com.mt/search* 
// @match          https://www.google.com.mt/?*q=* 
// @match          https://www.google.mu/search* 
// @match          https://www.google.mu/?*q=* 
// @match          https://www.google.mv/search* 
// @match          https://www.google.mv/?*q=* 
// @match          https://www.google.mw/search* 
// @match          https://www.google.mw/?*q=* 
// @match          https://www.google.com.mx/search* 
// @match          https://www.google.com.mx/?*q=* 
// @match          https://www.google.com.my/search* 
// @match          https://www.google.com.my/?*q=* 
// @match          https://www.google.co.mz/search* 
// @match          https://www.google.co.mz/?*q=* 
// @match          https://www.google.com.na/search* 
// @match          https://www.google.com.na/?*q=* 
// @match          https://www.google.ne/search* 
// @match          https://www.google.ne/?*q=* 
// @match          https://www.google.com.nf/search* 
// @match          https://www.google.com.nf/?*q=* 
// @match          https://www.google.com.ng/search* 
// @match          https://www.google.com.ng/?*q=* 
// @match          https://www.google.com.ni/search* 
// @match          https://www.google.com.ni/?*q=* 
// @match          https://www.google.nl/search* 
// @match          https://www.google.nl/?*q=* 
// @match          https://www.google.no/search* 
// @match          https://www.google.no/?*q=* 
// @match          https://www.google.com.np/search* 
// @match          https://www.google.com.np/?*q=* 
// @match          https://www.google.nr/search* 
// @match          https://www.google.nr/?*q=* 
// @match          https://www.google.nu/search* 
// @match          https://www.google.nu/?*q=* 
// @match          https://www.google.co.nz/search* 
// @match          https://www.google.co.nz/?*q=* 
// @match          https://www.google.com.om/search* 
// @match          https://www.google.com.om/?*q=* 
// @match          https://www.google.com.pa/search* 
// @match          https://www.google.com.pa/?*q=* 
// @match          https://www.google.com.pe/search* 
// @match          https://www.google.com.pe/?*q=* 
// @match          https://www.google.com.ph/search* 
// @match          https://www.google.com.ph/?*q=* 
// @match          https://www.google.com.pk/search* 
// @match          https://www.google.com.pk/?*q=* 
// @match          https://www.google.pl/search* 
// @match          https://www.google.pl/?*q=* 
// @match          https://www.google.com.pg/search* 
// @match          https://www.google.com.pg/?*q=* 
// @match          https://www.google.pn/search* 
// @match          https://www.google.pn/?*q=* 
// @match          https://www.google.com.pr/search* 
// @match          https://www.google.com.pr/?*q=* 
// @match          https://www.google.ps/search* 
// @match          https://www.google.ps/?*q=* 
// @match          https://www.google.pt/search* 
// @match          https://www.google.pt/?*q=* 
// @match          https://www.google.com.py/search* 
// @match          https://www.google.com.py/?*q=* 
// @match          https://www.google.com.qa/search* 
// @match          https://www.google.com.qa/?*q=* 
// @match          https://www.google.ro/search* 
// @match          https://www.google.ro/?*q=* 
// @match          https://www.google.rs/search* 
// @match          https://www.google.rs/?*q=* 
// @match          https://www.google.ru/search* 
// @match          https://www.google.ru/?*q=* 
// @match          https://www.google.rw/search* 
// @match          https://www.google.rw/?*q=* 
// @match          https://www.google.com.sa/search* 
// @match          https://www.google.com.sa/?*q=* 
// @match          https://www.google.com.sb/search* 
// @match          https://www.google.com.sb/?*q=* 
// @match          https://www.google.sc/search* 
// @match          https://www.google.sc/?*q=* 
// @match          https://www.google.se/search* 
// @match          https://www.google.se/?*q=* 
// @match          https://www.google.com.sg/search* 
// @match          https://www.google.com.sg/?*q=* 
// @match          https://www.google.sh/search* 
// @match          https://www.google.sh/?*q=* 
// @match          https://www.google.si/search* 
// @match          https://www.google.si/?*q=* 
// @match          https://www.google.sk/search* 
// @match          https://www.google.sk/?*q=* 
// @match          https://www.google.com.sl/search* 
// @match          https://www.google.com.sl/?*q=* 
// @match          https://www.google.sn/search* 
// @match          https://www.google.sn/?*q=* 
// @match          https://www.google.sm/search* 
// @match          https://www.google.sm/?*q=* 
// @match          https://www.google.so/search* 
// @match          https://www.google.so/?*q=* 
// @match          https://www.google.st/search* 
// @match          https://www.google.st/?*q=* 
// @match          https://www.google.com.sv/search* 
// @match          https://www.google.com.sv/?*q=* 
// @match          https://www.google.td/search* 
// @match          https://www.google.td/?*q=* 
// @match          https://www.google.tg/search* 
// @match          https://www.google.tg/?*q=* 
// @match          https://www.google.co.th/search* 
// @match          https://www.google.co.th/?*q=* 
// @match          https://www.google.com.tj/search* 
// @match          https://www.google.com.tj/?*q=* 
// @match          https://www.google.tk/search* 
// @match          https://www.google.tk/?*q=* 
// @match          https://www.google.tl/search* 
// @match          https://www.google.tl/?*q=* 
// @match          https://www.google.tm/search* 
// @match          https://www.google.tm/?*q=* 
// @match          https://www.google.to/search* 
// @match          https://www.google.to/?*q=* 
// @match          https://www.google.tn/search* 
// @match          https://www.google.tn/?*q=* 
// @match          https://www.google.com.tn/search* 
// @match          https://www.google.com.tn/?*q=* 
// @match          https://www.google.com.tr/search* 
// @match          https://www.google.com.tr/?*q=* 
// @match          https://www.google.tt/search* 
// @match          https://www.google.tt/?*q=* 
// @match          https://www.google.com.tw/search* 
// @match          https://www.google.com.tw/?*q=* 
// @match          https://www.google.co.tz/search* 
// @match          https://www.google.co.tz/?*q=* 
// @match          https://www.google.com.ua/search* 
// @match          https://www.google.com.ua/?*q=* 
// @match          https://www.google.co.ug/search* 
// @match          https://www.google.co.ug/?*q=* 
// @match          https://www.google.co.uk/search* 
// @match          https://www.google.co.uk/?*q=* 
// @match          https://www.google.us/search* 
// @match          https://www.google.us/?*q=* 
// @match          https://www.google.com.uy/search* 
// @match          https://www.google.com.uy/?*q=* 
// @match          https://www.google.co.uz/search* 
// @match          https://www.google.co.uz/?*q=* 
// @match          https://www.google.com.vc/search* 
// @match          https://www.google.com.vc/?*q=* 
// @match          https://www.google.co.ve/search* 
// @match          https://www.google.co.ve/?*q=* 
// @match          https://www.google.vg/search* 
// @match          https://www.google.vg/?*q=* 
// @match          https://www.google.co.vi/search* 
// @match          https://www.google.co.vi/?*q=* 
// @match          https://www.google.com.vn/search* 
// @match          https://www.google.com.vn/?*q=* 
// @match          https://www.google.vu/search* 
// @match          https://www.google.vu/?*q=* 
// @match          https://www.google.ws/search* 
// @match          https://www.google.ws/?*q=* 
// @match          https://www.google.co.za/search* 
// @match          https://www.google.co.za/?*q=* 
// @match          https://www.google.co.zm/search* 
// @match          https://www.google.co.zm/?*q=* 
// @match          https://www.google.co.zw/search* 
// @match          https://www.google.co.zw/?*q=*
// @run-at         document-start
// ==/UserScript==

/*
  #wikipedia: List of Google domains
  https://en.wikipedia.org/wiki/List_of_Google_domains
*/

function clean(selector, attr) {
  var els = document.querySelectorAll(selector);

  if (els.length) {
    for (var i in els) {
      els[i].removeAttribute(attr);
    }
  }
}

function doExec() {
  clean("#rso li.g a[onmousedown]", "onmousedown");
  clean(".irc_butc a[jsaction]", "jsaction");
}

document.addEventListener("DOMNodeInserted", doExec, false);
})();
